//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mail
{
    using System;
    using System.Collections.Generic;
    
    public partial class maildetail
    {
        public int mailid { get; set; }
        public int userid { get; set; }
        public string mailform { get; set; }
        public string sub { get; set; }
        public Nullable<System.DateTime> recieveddate { get; set; }
        public string mes { get; set; }
    
        public virtual userinfo userinfo { get; set; }
    }
}
